# Generated by Django 5.0.2 on 2024-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsapp', '0002_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
