# Generated by Django 5.0.3 on 2024-03-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsapp', '0005_case_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
