# Generated by Django 5.0.3 on 2024-03-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsapp', '0006_case_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
